### ISSUE TITLE
prob. with Quadro K2100M

### ISSUE THREAD

**Issue by zaz07** [hajhouj/fastsico#2]
**Summary:**
The program benchmark.cmd   is encountering errors and exceptions related to memory allocation and resource availability when querying different devices. The errors occur during the execution of the program and prevent it from completing successfully.

**Steps to Reproduce:**
1. Launch the program benchmark.cmd.
2. Enter a device query (e.g., '0.1').
3. Observe the errors and exceptions encountered during the execution of the program.
4. Repeat steps 2-3 with different device queries.

**Actual Results:**
1. When querying device '0.1' (Intel Core i7-4800MQ CPU @ 2.70GHz):
   - An OutOfMemoryError is encountered during the calculation of similarity in the dataset.
   - The Java heap space is exhausted, indicating a memory allocation issue.
   - The program terminates and provides an error message.
--> Exception: Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
        at java.nio.HeapIntBuffer.<init>(Unknown Source)
        at java.nio.IntBuffer.allocate(Unknown Source)
        at com.hajhouj.fastsico.factory.algorithm.EditDistance.calculateSimilarityInDataSet(EditDistance.java:143)
        at com.hajhouj.fastsico.StringSimilarity.calculateSimilarity(StringSimilarity.java:32)
        at com.hajhouj.fastsico.tools.Find.main(Find.java:50)

2. When querying device '1.0' (Quadro K2100M):
   - A CL_OUT_OF_RESOURCES exception is encountered multiple times during the execution.
   - The error occurs during the creation of a context and when trying to run a kernel.
   - The program terminates and provides an error message.
Exception: 
org.jocl.CLException: CL_OUT_OF_RESOURCES
        at org.jocl.CL.checkResult(CL.java:831)
        at org.jocl.CL.clEnqueueReadBuffer(CL.java:16415)
        at com.hajhouj.fastsico.factory.algorithm.EditDistance.runKernel(EditDistance.java:261)
        at com.hajhouj.fastsico.factory.algorithm.EditDistance.lambda$calculateSimilarityInDataSet$2(EditDistance.java:162)
        at java.util.Iterator.forEachRemaining(Unknown Source)
        at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Unknown Source)
        at java.util.stream.ReferencePipeline$Head.forEach(Unknown Source)
        at com.hajhouj.fastsico.factory.algorithm.EditDistance.calculateSimilarityInDataSet(EditDistance.java:159)
        at com.hajhouj.fastsico.StringSimilarity.calculateSimilarity(StringSimilarity.java:32)
        at com.hajhouj.fastsico.tools.Find.main(Find.java:50)

**Environment:**
- Operating System: Microsoft Windows [version 10.0.19044.2846]
- Java Version: java version "1.8.0_121"

**Comment by hajhouj** [comment]
After investigating on the error in other Nvidia gpu, It seems that updating the driver fix the problem

**Comment by zaz07** [comment]
I updated the driver to version 426.78-quadro-desktop-notebook-win10-64bit-international-dch-whql, but the problem still occurs :)
