### ISSUE TITLE
OutOfMemoryError when Querying Device Information

### ISSUE THREAD

**Issue by essadry** [hajhouj/fastsico#3]
**Issue Description:**
When attempting to query device information for the Intel(R) HD Graphics 520 (0.0) and Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz (0.1), an OutOfMemoryError occurs, leading to program termination.

**Steps to Reproduce:**

- Run the program benchmark.cmd.
- Enter device query "0.0" or "0.1" when prompted.
- Observe the program output.

**Actual Behavior:**
Upon entering the device query, the program throws an OutOfMemoryError related to the Java heap space.

**Error Message:**

Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
        at java.nio.HeapIntBuffer.<init>(Unknown Source)
        at java.nio.IntBuffer.allocate(Unknown Source)
        at com.hajhouj.fastsico.factory.algorithm.EditDistance.calculateSimilarityInDataSet(EditDistance.java:156)
        at com.hajhouj.fastsico.StringSimilarity.calculateSimilarity(StringSimilarity.java:32)
        at com.hajhouj.fastsico.tools.Find.main(Find.java:50)

**Environment:**

Operating System: Microsoft Windows [version 10.0.19044.2728]
Java Version: java version "1.8.0_251"

**Comment by hajhouj** [comment]
I figure out the origin of the issue, it's related to input buffer initialization. Try to download release 1.0.2 and test again.

**Comment by essadry** [comment]
Thank you for identifying the origin of the issue and suggesting the solution.

**Comment by hajhouj** [comment]
Please can you confirm bug resolution?
