### ISSUE TITLE
IllegalArgumentException in calculateSimilarityInDataSet method

### ISSUE THREAD

**Issue by AgbaniAyman** [hajhouj/fastsico#4]
Environment:

OS: Windows 10 
Java Version: jdk 20.0.1 
Device: Intel(R) HD Graphics 620
Description:
When running the calculateSimilarityInDataSet method in the com.hajhouj.fastsico.factory.algorithm.EditDistance class, the system throws an IllegalArgumentException: capacity < 0: (-221855232 < 0). This suggests that the system is attempting to allocate an IntBuffer with negative size.

Actual Result:
The system throws an IllegalArgumentException and is unable to recognize 'powershell' as a command.

Error Message:

Exception in thread "main" java.lang.IllegalArgumentException: capacity < 0: (-221855232 < 0)
        at java.base/java.nio.Buffer.createCapacityException(Buffer.java:284)
        at java.base/java.nio.IntBuffer.allocate(IntBuffer.java:373)
        at com.hajhouj.fastsico.factory.algorithm.EditDistance.calculateSimilarityInDataSet(EditDistance.java:156)
        at com.hajhouj.fastsico.StringSimilarity.calculateSimilarity(StringSimilarity.java:32)
        at com.hajhouj.fastsico.tools.Find.main(Find.java:50)

**Comment by hajhouj** [comment]
Bug fixed in 1.0.2. Please confirm bug resolution.

**Comment by AgbaniAyman** [comment]
Bug fixed
